server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://powerup.c11saxlcxtvw.us-east-1.rds.amazonaws.com/powerup
    username: admin
    password: admin123
  application:
    name: usuarios-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

hystrix:
  shareSecurityContext: true
feign:
  hystrix:
    enabled: true